### ISSUE TITLE
Webserver issues on container startup 

### ISSUE THREAD

**Issue by kheestand** [tiredofit/docker-fusiondirectory#12]
Hi,

I just ran a new container and noticed two issues.

The first issue is the nginx service does not start up automatically in the container. I had to go into the container and run the command <code>ngnix &</code> in order to run it.

Once the ngnix server was running, I navigated to the fusiondirectory webapp and got a php error: 
<code>
Fatal error: require(): Failed opening required '/usr/share/php/smarty3' (include_path='.:/www/fusiondirectory/include:/usr/share/php:/usr/share/php') in /www/fusiondirectory/include/php_setup.inc on line 339</code>

I was able to fix this error by changing line 339 in the php_setup.inc file to read 
<code>require('/usr/share/php/smarty3/smarty.class.php');</code> instead of <code>require('SMARTY');</code>

docker-compose.yml file used:
```
version: '3.7'
services:
  
  fusiondirectory-app:
    container_name: fusiondirectory-app
    restart: always
    image: tiredofit/fusiondirectory:alpine
    depends_on:
      - openldap-fusiondirectory
    environment:
      - VIRTUAL_HOST=fusiondirectory.example.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=fusiondirectory.example.org
      - LETSENCRYPT_EMAIL=yourname@example.org

      - ZABBIX_HOSTNAME=fusiondirectory-app

      - ENABLE_ARGONAUT=FALSE
      - PLUGIN_AUDIT=TRUE
      - PLUGIN_DSA=TRUE
      - PLUGIN_LDAPDUMP=TRUE
      - PLUGIN_LDAPMANAGER=TRUE
      - PLUGIN_MAIL=TRUE
      - PLUGIN_PERSONAL=TRUE
      - PLUGIN_PPOLICY=TRUE
      - PLUGIN_SSH=TRUE
      - PLUGIN_SUDO=TRUE
      - PLUGIN_WEBSERVICE=TRUE

      - LDAP1_HOST=openldap-fusiondirectory
      - LDAP1_BASE_DN=dc=example,dc=org
      - LDAP1_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP1_ADMIN_PASS=password
      - LDAP1_NAME=Production

    volumes:
      - ./logs:/www/logs

    networks:
      - proxy-tier


networks:
  proxy-tier:
    external:
name: nginx-proxy
```
