### ISSUE TITLE
Sample of docker-compose.yml for rancherOs

### ISSUE THREAD

**Issue by fruisoft** [tiredofit/docker-fusiondirectory#3]
Hi tiredofit !!
Can you put a sample of docker-compose.yml running the 2 services? (fusion and ldap)
Thanks

**Comment by tiredofit** [comment]
Sure, I keep them as seperate services on my production systems for easier CI deployment but here is a merged copy:

```
version: '2'

services:
  fd-example-com-app:
    image: tiredofit/fusiondirectory
    container_name: fd-example-com-app
    volumes:
    - ./hooks:/hooks
    - ./logs:/www/logs
    environment:
    - VIRTUAL_HOST=fd.example.com
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=fd.example.com
    - LETSENCRYPT_EMAIL=admin@example.com

    - ZABBIX_HOSTNAME=fd-example-com-app

    - PHP_MEMORY_LIMIT=512M
    - PHP_TIMEOUT=1800

    - ENABLE_ARGONAUT=FALSE
    - PLUGIN_AUDIT=TRUE
    - PLUGIN_DSA=TRUE
    - PLUGIN_LDAPDUMP=TRUE
    - PLUGIN_LDAPMANAGER=TRUE
    - PLUGIN_MAIL=TRUE
    - PLUGIN_MIXEDGROUPS=TRUE
    - PLUGIN_PERSONAL=TRUE
    - PLUGIN_POSIX=TRUE
    - PLUGIN_PPOLICY=TRUE
    - PLUGIN_SSH=TRUE
    - PLUGIN_SUDO=TRUE
    - PLUGIN_USER_REMINDER=TRUE
    - PLUGIN_WEBSERVICE=TRUE

    - PHP_ENABLE_OPCACHE=FALSE
    - PHP_ENABLE_APCU=FALSE
    
    - LDAP1_HOST=ldap-example-com-app
    - LDAP1_ADMIN_DN=cn=admin,dc=example,dc=com
    - LDAP1_ADMIN_PASS=supersecurepassword
    - LDAP1_BASE_DN=dc=example,dc=com
    - LDAP1_NAME=Production
    - LDAP1_PORT=389

    - DEBUG_MODE=FALSE
    networks:
      - proxy-tier
    restart: always

  ldap-example-com-app:
    container_name: ldap-example-com-app
    image: tiredofit/openldap-fusiondirectory:latest
    environment:
      - DEBUG_MODE=FALSE
      - HOSTNAME=ldap.example.com
      - LOG_LEVEL=256
      - ORGANIZATION="Example Organization"
      - DOMAIN=selfdesign.org
      - ADMIN_PASS=supersecurepassword
      - CONFIG_PASS=supersecureconfigpassword
      - REAPPLY_PLUGIN_SCHEMAS=TRUE
      - BASE_DN=dc=example,dc=com

      - ENABLE_TLS=true
      - TLS_CRT_FILENAME=ldap.crt
      - TLS_KEY_FILENAME=ldap.key
      - TLS_CA_CRT_FILENAME=ca.crt
      - TLS_VERIFY_CLIENT=never

      - ENABLE_REPLICATION=false

      - PLUGIN_AUDIT=TRUE
      - PLUGIN_DSA=TRUE
      - PLUGIN_LDAPDUMP=TRUE
      - PLUGIN_LDAPMANAGER=TRUE
      - PLUGIN_MAIL=TRUE
      - PLUGIN_MIXEDGROUPS=TRUE
      - PLUGIN_PERSONAL=TRUE
      - PLUGIN_POSIX=TRUE
      - PLUGIN_PPOLICY=TRUE
      - PLUGIN_SSH=TRUE
      - PLUGIN_SUDO=TRUE
      - PLUGIN_USER_REMINDER=TRUE
      - PLUGIN_WEBSERVICE=TRUE

      - PPOLICY_MIN_DIGIT=1
      - PPOLICY_MIN_LOWER=1
      - PPOLICY_MIN_UPPER=1
      - PPOLICY_MIN_PUNCT=1
      - PPOLICY_MIN_POINTS=4

      - ZABBIX_HOSTNAME=ldap-example-com-app
    hostname: ldap.example.com
    volumes:
      - ./backup:/data/backup
      - ./data:/var/lib/openldap
      - ./config:/etc/openldap/slapd.d
      - ./certs:/assets/slapd/certs
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
