### ISSUE TITLE
Error while editing configuration

### ISSUE THREAD

**Issue by b4cktr4ck5r3** [tiredofit/docker-fusiondirectory#43]
### Summary

I have an error while editing the configuration.

I tried first to remove "Force SSL" option on WebService Plugin configuration and the error above get displayed.

### Steps to reproduce

Just with simple configuration (use this container with the openldap-fusiondirectory container) : try to disable "Force SSL" from WebService plugins configuration.

### What is the expected *correct* behavior?

No error on FusionDirectory and get "Force SSL" for WebService disable

### Relevant logs and/or screenshots

I have no logs for this error even in Debug mode ...

![image](https://user-images.githubusercontent.com/59377281/117555103-95b3cb00-b05c-11eb-8a94-6fcf0db4eca3.png)

### Environment

- Image version / tag:  tiredofit/fusiondirectory:latest
- Host OS: Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

```
version: '3'
services:

  fusiondirectory-app:
    container_name: fusiondirectory-app
    image: tiredofit/fusiondirectory:latest
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:fusion-directory.m1miaa.fr
    - traefik.port=80
    - traefik.docker.network=nginx-proxy
    - traefik.backend=fusiondirectory-app
    volumes:
    - ./logs:/www/logs
    #- ./custom:/assets/fusiondirectory
    #- ./plugins-custom:/assets/plugins-custom
    environment:
    - DEBUG_MODE=FALSE
    - VIRTUAL_HOST=fusion-directory.m1miaa.fr
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=fusion-directory.m1miaa.fr

    - ZABBIX_HOSTNAME=fusiondirectory-app

    - ENABLE_ARGONAUT=FALSE
    - PLUGIN_AUDIT=TRUE
    - PLUGIN_DSA=TRUE
    - PLUGIN_LDAPDUMP=TRUE
    - PLUGIN_LDAPMANAGER=TRUE
    - PLUGIN_MAIL=TRUE
    - PLUGIN_PERSONAL=TRUE
    - PLUGIN_PPOLICY=TRUE
    - PLUGIN_SSH=TRUE
    - PLUGIN_SUDO=TRUE
    - PLUGIN_WEBSERVICE=TRUE

    - LDAP1_HOST=openldap-fusiondirectory-app
    - LDAP1_BASE_DN=dc=m1miaa,dc=fr
    - LDAP1_ADMIN_DN=cn=admin,dc=m1miaa,dc=fr
    - LDAP1_ADMIN_PASS=admin
    - LDAP1_PORT=389
    - LDAP1_NAME=Production

    #- LDAP2_BASE_DN=dc=example,dc=org
    #- LDAP2_ADMIN_DN=cn=admin,dc=example,dc=org
    #- LDAP2_HOST=openldap-fusiondirectory2
    #- LDAP2_ADMIN_PASS=password2
    #- LDAP2_NAME=Development
    #- LDAP2_TLS=TRUE
    networks:
    - proxy-tier
    restart: always

networks:
        proxy-tier:
                external:
                        name: nginx-proxy
```
    
### Possible fixes

No fix found for the moment
