### ISSUE TITLE
Could not connect to LDAP server

### ISSUE THREAD

**Issue by ViVlVl** [tiredofit/docker-fusiondirectory#50]
### Summary
When i try to connect to openldap, container add "cn=config,ou=fusiondirectory" on to searchbase:

### Relevant logs and/or screenshots

**OPENLDAP LOG:**
```

openldap         | 638db7d0 conn=1027 op=0 BIND dn="cn=admin,dc=pXXXX12,dc=XX" method=128
openldap         | 638db7d0 conn=1027 op=0 BIND dn="cn=admin,dc=pXXXX12,dc=XX" mech=SIMPLE ssf=0
openldap         | 638db7d0 conn=1027 op=0 RESULT tag=97 err=0 text=
openldap         | 638db7d0 conn=1027 op=1 SRCH base="cn=config,ou=fusiondirectory,dc=pХХХХ12,dc=ХХ" scope=0 deref=0 filter="(objectClass=*)"

```

### Environment

part of docker-compose.yml:

```
  fusiondirectory:
    container_name: fusiondirectory
    image: tiredofit/fusiondirectory
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:fd.pХХХХ12.XX
      - traefik.port=80
      #- traefik.docker.network=proxy
      - traefik.backend=fusiondirectory
    ports:
      - "8090:80"
    volumes:
      - /home/medcloud/fd/logs:/www/logs
      - /home/medcloud/fd/custom:/assets/fusiondirectory
      - /home/medcloud/fd/plugins-custom:/assets/plugins-custom
    environment:
      - VIRTUAL_HOST=fd.pХХХХ12.XX
      #- VIRTUAL_NETWORK=proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=fd.pХХХХ12.XX
      - LETSENCRYPT_EMAIL=XX@XX.XX
      - PHP_LOG_LEVEL=debug
      - CONTAINER_NAME=fusiondirectory
      - ENABLE_ARGONAUT=FALSE
      - PLUGIN_AUDIT=TRUE
      - PLUGIN_DSA=TRUE
      - PLUGIN_LDAPDUMP=TRUE
      - PLUGIN_LDAPMANAGER=TRUE
      - PLUGIN_MAIL=TRUE
      - PLUGIN_PERSONAL=TRUE
      - PLUGIN_PPOLICY=TRUE
      - PLUGIN_SSH=TRUE
      - PLUGIN_SUDO=TRUE
      - PLUGIN_WEBSERVICE=TRUE
      - LDAP1_HOST=openldap
      - LDAP1_BASE_DN=dc=pХХХХ12,dc=XX
      - LDAP1_ADMIN_DN=cn=admin,dc=pХХХХ12,dc=XX
      - LDAP1_ADMIN_PASS=superpass
      - LDAP1_PORT=389
      - LDAP1_NAME=pol12
    #- LDAP2_BASE_DN=dc=example,dc=org
    #- LDAP2_ADMIN_DN=cn=admin,dc=example,dc=org
    #- LDAP2_HOST=openldap-fusiondirectory2
    #- LDAP2_ADMIN_PASS=password2
    #- LDAP2_NAME=Development
    #- LDAP2_TLS=TRUE
    networks:
      - medcloud
    restart: always

```
inside container, cat /etc/fusiondirectory/fusiondirectory.conf all ok:

```
bash-4.4# cat fusiondirectory.conf 
<?xml version="1.0"?>
<conf>
  <main default="pol12"
        logging="TRUE"
        displayErrors="FALSE"
        forceSSL="FALSE"
        templateCompileDirectory="/var/spool/fusiondirectory/"
        debugLevel="0"
    >

  <location name="pol12" ldapTLS="">
      <referral URI='ldap://openldap:389/dc=pХХХХ12,dc=XX'
                      adminDn="ccn=admin,dc=pХХХХ12,dc=XX"
                      adminPassword="superpass" />
  </location>
  </main>
</conf>
```
