### ISSUE TITLE
Could not connect to LDAP server

### ISSUE THREAD

**Issue by XVicarious** [tiredofit/docker-fusiondirectory#9]
So I've been playing with this image and its companion image for several months, on and off. I have yet to get it to work.

```
version: '3.7'

services:

  fusion:
    image: tiredofit/fusiondirectory
    environment:
      - ENABLE_ARGONAUT=FALSE
      - LDAP1_HOST=ldap.example.com
      - LDAP1_BASE_DN=dc=example,dc=com
      - LDAP1_ADMIN_DN=cn=admin,dc=example,dc=com
      - LDAP1_ADMIN_PASS=admin
      - LDAP1_NAME=example
      - LDAP1_TLS=TRUE
      - PHP_LOG_LEVEL=debug
    labels:
      traefik.enable: "true"
      traefik.docker.network: 'traefik_traefik'
      traefik.frontend.rule: "Host:fd.example.com"
    volumes:
      - /home/docker/ldap/logs:/www/logs
    networks:
      - traefik
      - default
      
  ldap:
    hostname: ldap.example.com
    domainname: ldap.example.com
    image: tiredofit/openldap-fusiondirectory
    ports:
      - 389:389
      - 636:636
    environment:
      - HOSTNAME=ldap.example.com
      - BACKEND=mdb
      - DOMAIN=example.com
      - ADMIN_PASS=admin
      - CONFIG_PASS=config
      - FUSIONDIRECTORY_ADMIN_USER=fd-admin
      - FUSIONDIRECTORY_ADMIN_PASS=admin
      - ORGANIZATION=Example
      - BASE_DN=dc=example,dc=com
      - ENABLE_READONLY_USER=false
      - ENABLE_TLS=true
      - TLS_CRT_FILENAME=cert.pem
      - TLS_KEY_FILENAME=key.pem
      - TLS_CA_CRT_FILENAME=ca.pem
      - TLS_ENFORCE=false
      - TLS_CIPHER_SUITE=ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:-DHE-DSS:-RSA:!aNULL:!MD5:!DSS:!SHA
      - TLS_VERIFY_CLIENT=never
      - SSL_HELPER_PREFIX=ldap
      - ENABLE_REPLICATION=false
      - BACKUP_CONFIG_CRON_PERIOD=0 4 * * *
      - BACKUP_DATA_CRON_PERIOD=0 4 * * *
      - BACKUP_TTL=15
    labels:
      traefik.enable: 'true'
      traefik.port: 80
      traefik.frontend.rule: 'Host:ldap.example.com'
    volumes:
      - /home/docker/ldap/backup:/data/backup
      - /home/docker/ldap/data:/var/lib/openldap
      - /home/docker/ldap/config:/etc/openldap/slapd.d
      - /home/docker/certs:/assets/slapd/certs

networks:
  traefik:
    external: true
    name: traefik_traefik
```

This is my docker-compose file. I am running in swarm mode.

Enabling debug mode doesn't give me much information. Just a stacktrace that really doesn't give any more specifics. All that it shows is the trace to display the error. It does give the params it used `ldaps://ldap.example.com:`, `dc=example,dc=com`, `cn=admin,dc=example,dc=com`

When I enter the container with `... exec ... /bin/bash` I can execute `ldapsearch -h ldap.example.com -b dc=example,dc=me -D cn=admin,dc=xvss,dc=me -w admin -Z` and it successfully connects and spits out results.

Even when I turn off TLS for FusionDirectory and connect via the default non-secure port I get the same issue. The container can find and connect to the openldap instance and container its hosted in fine, but it appears PHP can't.

Any insight on this? More information that you could use? It could just be a silly tiny mistake I made somewhere.
